### ISSUE TITLE
Fails in Firefox 44 beta

### ISSUE THREAD

**Issue by Dimas-sc** [Lemutar/Synoloader#30] opened 2016-01-09 20:22 UTC
It seems this plugin stops working in Firefox 44 beta. It doesn't load the list of current downloads. It also prevents you from downloading any file from the web, as clicking 'Save' in the standard Firefox download dialog does nothing when this addon is enabled.

**Comment by noplanman** [comment] 2016-01-10 13:00
Hi @Dimas-sc, thanks for letting us know.
I saw your review on the Firefox plugin page as well but haven't replied there yet, so I'll just do it here :blush: 

Regarding the beta, we'll have a look into it and see why it doesn't work, but sometimes beta is just that, beta, not ready or finished yet. I've seen it in another project, that there was a problem with the beta that then disappeared when the finished version was released.
So trying to fix something when the base software is in beta can be a bit of a pain, as it might change again before the release.

Anyway thanks for pointing it out! I'll see what the problem is and hopefully we can fix it.

We'll definitely make sure that everything works for the released version of Firefox 44 though :+1:

**Comment by Dimas-sc** [comment] 2016-01-10 13:41
Well, the review on the Firefox plugin page isn't mine, but as I've the same problem I copied the text here :-) Since from the actual Firefox Beta to the official release only bugfixes will occur I think it should be good to look at it.

Thx!

**Comment by noplanman** [comment] 2016-01-10 13:44
Yep, I realised it wasn't yours after I commented here, sorry about that.

You're right regarding the bugfixes, we'll check it out :smiley:

**Comment by noplanman** [comment] 2016-01-10 21:54
@Lemutar, this seems to be a lot bigger than I thought.

The issue seems to be [Firefox's Multiprocess](https://developer.mozilla.org/en-US/Firefox/Multiprocess_Firefox) which has become the default in Firefox 44.
In my view, if at all possible, would be to port the addon to use the Addon SDK. I remember you said that something wouldn't work with the SDK, right? Well it seems like we're going to have to find some kind of solution for that.

Code-rewrite, here we come...

**Comment by Dimas-sc** [comment] 2016-01-10 22:02
How can I check if I've multiprocess enabled in 44 Beta? The Firefox's Multiprocess page says that "Multiprocess Firefox is currently enabled by default in Developer Edition builds".

**Comment by noplanman** [comment] 2016-01-10 22:21
I don't know if there is a way to check but what I've noticed is that there is no option any more to enable or disable it, as has been the case till now.
Also, check [this post](https://blog.mozilla.org/addons/2016/01/06/add-ons-update-75/) and scroll down to the section called "Electrolysis". It states there that Firefox now uses Multiprocess.

Strangely enough though, having Multiprocess enabled in the Developer Edition doesn't make the addon fail, it works perfectly fine. So I'm really not sure yet if the culprit really *is* Multiprocess...

It would make sense though, since only part of SynoLoader loads. There is no error output or anything, the other code just isn't executed, probably as it is run by another process, at least this is my interpretation of it so far.
I'm still very new to extension development and am a bit confused at the moment :confused: 

@Lemutar, seems like what we need to look into is [WebExtensions](https://wiki.mozilla.org/WebExtensions), as this seems to be the future.

**Comment by Lemutar** [comment] 2016-01-11 09:01
I'm back from my vacation now and will take a look in to this. I hope we do not have the hole implementation at once.

**Comment by noplanman** [comment] 2016-01-11 09:18
@Lemutar Welcome back!
Me too, I hope we can find a simple solution for now and have more time to look into porting it to the new Firefox way.
Will be great to have it fully ported at some point :smiley:

**Comment by noplanman** [comment] 2016-01-11 09:31
@Dimas-sc, regarding the Multiprocess checking, you should be able to find 2 processes in your Task Manager / Activity Monitor:
- Firefox
- Firefox Web Content

Or with the Developer Edition:
- FirefoxDeveloperEdition
- FirefoxDeveloperEdition Web Content

Obviously, if you see both, you're using Multiprocess :+1:

**Comment by Dimas-sc** [comment] 2016-01-11 10:48
44 beta doesn't seem to have Multiprocess enabled: https://i.imgur.com/xExSmpI.png. I don't really think Multiprocess is enabled in beta yet.

But I'm tried with Firefox Trunk forcing Multiprocess enabled and I can't see the process 'Firefox Web Content' either: https://i.imgur.com/tSDbsWL.png

**Comment by noplanman** [comment] 2016-01-11 13:25
Ok, maybe the the Windows version manages it differently?
I'm on OSX and see both processes. If I disable Multiprocess I see only one.
Using 44 Beta I see both, with no option to disable it.

I've installed it on Windows as well and see the same thing as you (obviously). Only 1 process, `firefox.exe`. So I honestly don't know how this Multiprocess thing works on the different platforms.

**Comment by Lemutar** [comment] 2016-01-11 17:48
it looks like the remove of 
let {
    classes: Cc,
    interfaces: Ci,
    utils: Cu
} = Components;

in src/chrome/content/ff-overlay.js
fix the problem for me. Firefox was complaining about duplicated definitions.
Can some verify this results ?

**Comment by noplanman** [comment] 2016-01-11 18:50
Yep, works for me also removing those definitions.
Where did you see Firefox complaining about duplicates? Didn't get that anywhere in the console.
I read somewhere in the logs that `let` and `const` have been polished, which may have caused the problem I guess.

I agree that it's strange that it works on FF 45, you're talking about the Developer Edition, yes?

@Lemutar awesome find!

**Comment by azevedo-manuel** [comment] 2016-01-27 09:38
I confirm it's not working on Firefox 44 (the official came out yesterday) either on the Mac or in Windows. It hijacks the Save button and only disabling the Plugin allows downloads to work again.

**Comment by noplanman** [comment] 2016-01-27 10:00
@azevedo-manuel I noticed that as well regarding the hijacking of the save dialog.
@Lemutar, could you add the fix you've found and update the plugin? Especially that Firefox 44 isn't in Beta anymore, thanks!

**Comment by noplanman** [comment] 2016-01-31 19:38
This issue is fixed via #34

**Closed by noplanman** 2016-01-31 19:38 UTC
